name: CI/CD Pipeline

on:
  push:
    branches:
      - prod

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.0

      - name: Install Dependencies
        run: pnpm install

      - name: Load .env file
        uses: natterstefan/action-next-env@v1

      - name: Check if GH_ACCESS_TOKEN is defined
        run: |
          if [ -z "${{ secrets.GH_ACCESS_TOKEN }}" ]; then
            echo "GH_ACCESS_TOKEN is not defined. Please add the secret in your repository settings."
            exit 1
          else
            echo "GH_ACCESS_TOKEN is defined."
          fi

      - name: Deploy to AWS
        run: pnpm sst deploy --stage prod
        env:
          GH_ACCESS_TOKEN: ${{ env.GH_ACCESS_TOKEN }}
